language: go
sudo: false
go:
- 1.4
- 1.5
install:
- DST=~/gopath/src/github.com/nats-io
- mkdir -p "$DST"
- git clone --depth=1 --quiet https://github.com/nats-io/gnatsd.git "$DST"/gnatsd
- go get -t ./...
- go get golang.org/x/tools/cmd/vet
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- go fmt ./...
- go vet ./...
- go test -i -race ./...
- go test -v -race ./...
- go test -v -covermode=count -coverprofile=coverage.out ./...
- $HOME/gopath/bin/goveralls -coverprofile coverage.out -service travis-ci
env:
  global:
    secure: UxWSqs4k2Sa2AqA16rbRYxkqw9eF82yjl737CCCf2ce6nQTihZ2zNOPDXMfE/JeKv6spwErzX3I2JyrSQJ9BdHTwnYHOdvajNFqoUDtM/vp89OcOBrUNNST0wlmVp8mkMSUecpBAJCaCpc8PTbkca2p7VkHv8dohdSnpxugPZX0=
