language: go

before_script:
  - gem -v
  - ruby -v
  - gem install nats --pre
  - which nats-server
  - nats-server -v
  - go version
  - mkdir -p $GOPATH/src/github.com/apcera
  - ln -s /home/travis/build/apcera/nats nats
